import { useEffect, useRef, useState, forwardRef, useImperativeHandle } from 'react'
import { EditorView, keymap, ViewUpdate } from '@codemirror/view'
import { EditorState } from '@codemirror/state'
import { defaultKeymap, historyKeymap, history } from '@codemirror/commands'
import { markdown } from '@codemirror/lang-markdown'
import { gravitas } from './theme'
import { wikilinkPlugin } from './plugins/wikilinks'
import { openQuestionPlugin } from './plugins/openQuestions'
import { typewriterExtensions, setProgrammatic } from './plugins/typewriter'
import { focusGradient } from './plugins/activeLine'
import { playKeySound } from './plugins/typewriterSound'
import { markdownRenderPlugin } from './plugins/markdownRender'
import { createPasteIntentPlugin } from './plugins/pasteIntent'
import { processBlockPlugin } from './plugins/processBlock'
import { createScratchPromotePlugin, scratchReadonlyExtension } from './plugins/scratchPromote'
import { exportNoteAsPdf } from '../export/exportPdf'
import { renderMarkdown } from '../read/renderMarkdown'
import { loadReviews, locateReview, makeReview, saveReviews, type ReviewKind, type ReviewMark } from '../review/reviewStore'
import ShareReviewPanel from '../share/ShareReviewPanel'
import './pasteBanner.css'
import './Editor.css'

interface Note { title:string; path:string; content:string; meta:{date:string;tags:string[];type:string;words:number} }
type EditorMode='write'|'read'|'audit'
export interface EditorHandle { appendEntry:(text:string)=>void; insertAt:(pos:number,text:string)=>void; getView:()=>EditorView|null; reloadReviews:()=>Promise<void> }
interface EditorProps { note:Note; onNavOpen:()=>void; onContentChange?:(content:string)=>void; onTitleChange?:(newTitle:string)=>void; saveState?:'set'|'setting'|'unsaved'; soundEnabled?:boolean; pasteIntentEnabled?:boolean; isScratch?:boolean; isNewNote?:boolean; onNewNoteDone?:()=>void; onPromote?:(content:string,insertAfterPos:number)=>void; onDeleteEntry?:(dividerLineNo:number)=>void }
const countWords=(t:string)=>t.trim().split(/\s+/).filter(Boolean).length
const readingTime=(w:number)=>{const m=Math.ceil(w/200);return m<1?'< 1 min':`~${m} min read`}
const pathTitle=(p:string)=>{const r=p.split('/').pop()?.replace(/\.md$/,'')??'';return r&&r!=='untitled'?r:''}
const kindLabel:Record<ReviewKind,string>={comment:'Comment',revisit:'Revisit',question:'Question',cut:'Cut?'}
const reviewExcerpt=(text:string,max=180)=>{const clean=text.replace(/\s+/g,' ').trim();return clean.length<=max?clean:`${clean.slice(0,max).trimEnd()}…`}
function paintReadReviews(root:HTMLElement,reviews:ReviewMark[]){root.querySelectorAll('.gv-review-overlay,.gv-review-margin-mark').forEach(mark=>mark.remove());const locate=(needle:string):Range|null=>{if(!needle)return null;const full=root.textContent??'',start=full.indexOf(needle);if(start<0)return null;const end=start+needle.length,walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node:Node|null=walker.nextNode(),offset=0,startNode:Node|null=null,endNode:Node|null=null,startOffset=0,endOffset=0;while(node){const length=node.textContent?.length??0;if(!startNode&&start>=offset&&start<=offset+length){startNode=node;startOffset=start-offset}if(endNode===null&&end>=offset&&end<=offset+length){endNode=node;endOffset=end-offset;break}offset+=length;node=walker.nextNode()}if(!startNode||!endNode)return null;const range=document.createRange();range.setStart(startNode,startOffset);range.setEnd(endNode,endOffset);return range};const rootRect=root.getBoundingClientRect();reviews.filter(r=>r.status==='open').forEach(review=>{const range=locate(review.selectedText);if(!range)return;const rects=Array.from(range.getClientRects()).filter(rect=>rect.width&&rect.height);rects.forEach(rect=>{const line=document.createElement('i');line.className='gv-review-overlay';line.style.left=`${rect.left-rootRect.left+root.scrollLeft}px`;line.style.top=`${rect.bottom-rootRect.top+root.scrollTop-2}px`;line.style.width=`${rect.width}px`;root.appendChild(line)});const first=rects[0];if(first){const tick=document.createElement('i');tick.className='gv-review-margin-mark';tick.style.top=`${first.top-rootRect.top+root.scrollTop+Math.max(5,first.height*.45)}px`;root.appendChild(tick)}})}
const Editor=forwardRef<EditorHandle,EditorProps>(function Editor({note,onNavOpen,onContentChange,onTitleChange,saveState='set',soundEnabled=false,pasteIntentEnabled=true,isScratch=false,isNewNote=false,onNewNoteDone,onPromote,onDeleteEntry},ref){
 const editorRef=useRef<HTMLDivElement>(null),viewRef=useRef<EditorView|null>(null),readRef=useRef<HTMLElement>(null)
 const [words,setWords]=useState(countWords(note.content)),[chars,setChars]=useState(note.content.length),[uiVisible,setUiVisible]=useState(false),[shortcutsOpen,setShortcutsOpen]=useState(false),[shareOpen,setShareOpen]=useState(false),[mode,setMode]=useState<EditorMode>('write'),[readContent,setReadContent]=useState(note.content)
 const [reviews,setReviews]=useState<ReviewMark[]>([]),[activeReview,setActiveReview]=useState(0),[reviewSelection,setReviewSelection]=useState(''),[reviewPoint,setReviewPoint]=useState<{x:number;y:number}|null>(null),[commenting,setCommenting]=useState(false),[commentDraft,setCommentDraft]=useState('')
 const uiTimerRef=useRef<ReturnType<typeof setTimeout>|null>(null),activeKeyRef=useRef(''),soundEnabledRef=useRef(soundEnabled),pasteIntentEnabledRef=useRef(pasteIntentEnabled),isScratchRef=useRef(isScratch)
 const [editingTitle,setEditingTitle]=useState(false),[titleDraft,setTitleDraft]=useState(''),titleInputRef=useRef<HTMLInputElement>(null),commentInputRef=useRef<HTMLInputElement>(null),[pasteBannerVisible,setPasteBannerVisible]=useState(false),[entering,setEntering]=useState(false)
 const onPromoteRef=useRef(onPromote),onDeleteEntryRef=useRef(onDeleteEntry)
 useEffect(()=>{soundEnabledRef.current=soundEnabled},[soundEnabled]);useEffect(()=>{pasteIntentEnabledRef.current=pasteIntentEnabled},[pasteIntentEnabled]);useEffect(()=>{isScratchRef.current=isScratch},[isScratch]);useEffect(()=>{onPromoteRef.current=onPromote},[onPromote]);useEffect(()=>{onDeleteEntryRef.current=onDeleteEntry},[onDeleteEntry])
 const reloadReviews=async()=>setReviews(await loadReviews(note.path))
 useImperativeHandle(ref,()=>({appendEntry(text){const v=viewRef.current;if(!v)return;const n=v.state.doc.length;v.dispatch({changes:{from:n,insert:text},selection:{anchor:n+text.length},scrollIntoView:true})},insertAt(pos,text){viewRef.current?.dispatch({changes:{from:pos,insert:text}})},getView(){return viewRef.current},reloadReviews}))
 const showUI=(e:React.MouseEvent)=>{if(e.movementX===0&&e.movementY===0)return;setUiVisible(true);if(uiTimerRef.current)clearTimeout(uiTimerRef.current);uiTimerRef.current=setTimeout(()=>setUiVisible(false),2500)}
 const displayTitle=pathTitle(note.path)||note.title,currentContent=()=>viewRef.current?.state.doc.toString()??note.content,openReviews=reviews.filter(r=>r.status==='open')
 const handleTitleClick=()=>{if(!onTitleChange||mode!=='write')return;setTitleDraft(displayTitle);setEditingTitle(true);setTimeout(()=>titleInputRef.current?.select(),0)},handleTitleCommit=()=>{setEditingTitle(false);const t=titleDraft.trim();if(!t||t===displayTitle)return;onContentChange?.(currentContent());setTimeout(()=>onTitleChange?.(t),900)},handleTitleKeyDown=(e:React.KeyboardEvent)=>{if(e.key==='Enter')handleTitleCommit();if(e.key==='Escape')setEditingTitle(false)}
 const changeMode=(next:EditorMode)=>{if(isScratch&&next!=='write')return;if(next==='read')setReadContent(currentContent());setShortcutsOpen(false);setShareOpen(false);setReviewPoint(null);setCommenting(false);setMode(next);if(next==='audit')setActiveReview(0)},persistReviews=async(next:ReviewMark[])=>{setReviews(next);await saveReviews(note.path,next)},clearReviewSelection=()=>{setReviewSelection('');setReviewPoint(null);setCommenting(false);setCommentDraft('');window.getSelection()?.removeAllRanges()},addReview=async(kind:ReviewKind,comment='')=>{if(!reviewSelection.trim())return;const next=[...reviews,makeReview(kind,reviewSelection,readContent,comment)];setReviews(next);clearReviewSelection();requestAnimationFrame(()=>{if(readRef.current)paintReadReviews(readRef.current,next)});await saveReviews(note.path,next)},beginComment=()=>{setCommenting(true);setTimeout(()=>commentInputRef.current?.focus(),0)}
 const handleReadSelection=()=>{if(mode!=='read'||commenting)return;const selection=window.getSelection(),text=selection?.toString().trim()??'';if(!text||!selection?.rangeCount){setReviewPoint(null);setReviewSelection('');return}const range=selection.getRangeAt(0);if(!readRef.current?.contains(range.commonAncestorContainer))return;const rect=range.getBoundingClientRect();setReviewSelection(text);setReviewPoint({x:Math.min(window.innerWidth-180,rect.left+rect.width/2),y:Math.max(46,rect.top-8)})}
 const goReview=(index:number)=>{if(!openReviews.length)return;const next=(index+openReviews.length)%openReviews.length;setActiveReview(next);const target=openReviews[next],v=viewRef.current;if(!v)return;const found=locateReview(target,v.state.doc.toString());if(!found)return;v.dispatch({selection:{anchor:found.from,head:found.to},scrollIntoView:true});requestAnimationFrame(()=>{v.focus();const coords=v.coordsAtPos(found.from);if(!coords)return;const scroller=v.scrollDOM,scrollerRect=scroller.getBoundingClientRect(),desired=scrollerRect.top+Math.min(scrollerRect.height*.34,220);scroller.scrollTop+=coords.top-desired;requestAnimationFrame(()=>v.focus())})},resolveActive=async()=>{const target=openReviews[activeReview];if(!target)return;const next=reviews.map(r=>r.id===target.id?{...r,status:'resolved' as const,resolvedAt:new Date().toISOString()}:r);await persistReviews(next);setActiveReview(Math.min(activeReview,Math.max(0,next.filter(r=>r.status==='open').length-1)))}
 const pastePluginRef=useRef<ReturnType<typeof createPasteIntentPlugin>|null>(null);if(!pastePluginRef.current)pastePluginRef.current=createPasteIntentPlugin(s=>setPasteBannerVisible(s.active),pasteIntentEnabledRef);const promotePluginRef=useRef<ReturnType<typeof createScratchPromotePlugin>|null>(null);if(!promotePluginRef.current)promotePluginRef.current=createScratchPromotePlugin(onPromoteRef,onDeleteEntryRef)
 useEffect(()=>{if(!editorRef.current)return;const state=EditorState.create({doc:note.content,extensions:[history(),keymap.of([...defaultKeymap,...historyKeymap]),markdown(),gravitas,wikilinkPlugin,openQuestionPlugin,markdownRenderPlugin,processBlockPlugin,focusGradient,...(pastePluginRef.current?[pastePluginRef.current]:[]),...(promotePluginRef.current?[promotePluginRef.current]:[]),scratchReadonlyExtension(()=>isScratchRef.current),...typewriterExtensions,EditorView.domEventHandlers({keydown(e){if(!soundEnabledRef.current)return false;if(e.key.length===1||e.key==='Enter'||e.key==='Backspace'||e.key==='Delete')playKeySound();return false}}),EditorView.updateListener.of((u:ViewUpdate)=>{if(u.docChanged){const text=u.state.doc.toString();setWords(countWords(text));setChars(text.length);onContentChange?.(text)}}),EditorView.lineWrapping]});const v=new EditorView({state,parent:editorRef.current});viewRef.current=v;activeKeyRef.current=note.path;const end=v.state.doc.length;v.dispatch({selection:{anchor:end},scrollIntoView:false});requestAnimationFrame(()=>{v.scrollDOM.scrollTop=v.scrollDOM.scrollHeight});v.focus();return()=>v.destroy()},[])
 useEffect(()=>{let alive=true;loadReviews(note.path).then(r=>{if(alive)setReviews(r)});return()=>{alive=false}},[note.path]);useEffect(()=>{const v=viewRef.current;if(!v||note.path===activeKeyRef.current)return;activeKeyRef.current=note.path;setMode('write');setShareOpen(false);setReadContent(note.content);setReviews([]);setProgrammatic(true);v.dispatch({changes:{from:0,to:v.state.doc.length,insert:note.content},scrollIntoView:false});setWords(countWords(note.content));setChars(note.content.length);requestAnimationFrame(()=>{const end=v.state.doc.length;v.dispatch({selection:{anchor:end},scrollIntoView:false});v.scrollDOM.scrollTop=v.scrollDOM.scrollHeight;requestAnimationFrame(()=>{setProgrammatic(false);v.focus()})});if(isNewNote){setEntering(true);const t=setTimeout(()=>setEntering(false),300);if(!isScratch){setTitleDraft(pathTitle(note.path)||note.title);setEditingTitle(true);setTimeout(()=>titleInputRef.current?.select(),80)}onNewNoteDone?.();return()=>clearTimeout(t)}},[note.path,note.content])
 useEffect(()=>{const v=viewRef.current;if(!v)return;v.contentDOM.spellcheck=false;if(mode==='write')requestAnimationFrame(()=>v.focus());if(mode==='audit'&&openReviews.length)requestAnimationFrame(()=>goReview(0))},[mode]);useEffect(()=>{if(mode!=='audit'||!openReviews.length)return;requestAnimationFrame(()=>goReview(activeReview))},[mode,activeReview,reviews]);useEffect(()=>{if(mode!=='read'||!readRef.current)return;const root=readRef.current,frame=requestAnimationFrame(()=>paintReadReviews(root,openReviews));return()=>cancelAnimationFrame(frame)},[mode,readContent,reviews,uiVisible])
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&['1','2','3'].includes(e.key)){e.preventDefault();changeMode(e.key==='1'?'write':e.key==='2'?'read':'audit');return}if(mode==='read'){if(e.key==='Escape'){e.preventDefault();if(commenting)clearReviewSelection();else changeMode('write');return}if(reviewSelection&&!commenting&&!e.metaKey&&!e.ctrlKey&&!e.altKey){const k=e.key.toLowerCase();if(k==='c'){e.preventDefault();beginComment()}else if(k==='r'){e.preventDefault();void addReview('revisit')}else if(e.key==='?'){e.preventDefault();void addReview('question')}else if(k==='x'){e.preventDefault();void addReview('cut')}}}if(mode==='audit'&&(e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();void resolveActive()}if(mode==='audit'&&e.altKey&&e.key==='ArrowDown'){e.preventDefault();goReview(activeReview+1)}if(mode==='audit'&&e.altKey&&e.key==='ArrowUp'){e.preventDefault();goReview(activeReview-1)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[mode,reviewSelection,commenting,reviews,activeReview,readContent])
 const saveLabel=saveState==='set'?'Set':saveState==='setting'?'Setting…':'Not set',handleExportPdf=()=>exportNoteAsPdf(displayTitle,currentContent()),mod=/Mac|iPhone|iPad/.test(navigator.platform)?'⌘':'Ctrl',active=openReviews[activeReview]
 return <div className={`gv-editor gv-mode-${mode} ${uiVisible||shortcutsOpen||shareOpen?'ui-visible':''}`} onMouseMove={showUI}><div className="gv-topbar"><button className="gv-nav-toggle" onClick={onNavOpen} title="Navigate"><span/><span/><span/></button><div className="gv-topbar-actions"><button className={`gv-mode-tab ${mode==='write'?'active':''}`} onClick={()=>changeMode('write')}>Write</button><button className={`gv-mode-tab ${mode==='read'?'active':''} ${isScratch?'gv-mode-tab-disabled':''}`} onClick={()=>changeMode('read')}>Read</button><button className={`gv-mode-tab ${mode==='audit'?'active':''} ${isScratch?'gv-mode-tab-disabled':''}`} onClick={()=>changeMode('audit')}>Audit</button></div></div>
 {mode==='write'&&<div className={`gv-paste-banner ${pasteBannerVisible?'visible':''}`}><span><span className="gv-paste-banner-key">Q</span> quote</span><span className="gv-paste-banner-sep">·</span><span><span className="gv-paste-banner-key">P</span> process</span><span className="gv-paste-banner-sep">·</span><span>any key plain</span></div>}
 <div className={`gv-stage ${entering?'gv-entering':''}`}><div className="gv-col"><div className="gv-header">{isScratch?<div className="gv-scratch-label">scratch</div>:editingTitle&&mode==='write'?<input ref={titleInputRef} className="gv-title gv-title-input" value={titleDraft} onChange={e=>setTitleDraft(e.target.value)} onBlur={handleTitleCommit} onKeyDown={handleTitleKeyDown}/>:<h1 className={`gv-title ${onTitleChange&&mode==='write'?'gv-title-editable':''}`} onClick={handleTitleClick}>{displayTitle}</h1>}{!isScratch&&<div className="gv-meta"><span>{note.meta.date}</span>{note.meta.tags.map(t=><span key={t} className="gv-tag">{t}</span>)}<span className="gv-type-badge">{note.meta.type}</span>{mode!=='write'&&openReviews.length>0&&<span>{openReviews.length} open review{openReviews.length===1?'':'s'}</span>}</div>}</div><div className={`gv-cm-wrap ${mode==='read'?'gv-surface-hidden':''}`} ref={editorRef}/>{mode==='read'&&<article ref={readRef} className="gv-read" onMouseUp={handleReadSelection} dangerouslySetInnerHTML={{__html:renderMarkdown(readContent)}}/>}</div></div>
 {mode==='read'&&reviewPoint&&<div className="gv-review-popover" style={{left:reviewPoint.x,top:reviewPoint.y}}>{commenting?<input ref={commentInputRef} value={commentDraft} placeholder="Leave a note…" onChange={e=>setCommentDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void addReview('comment',commentDraft)}if(e.key==='Escape'){e.preventDefault();clearReviewSelection()}}}/>:<><button onClick={beginComment}><kbd>C</kbd> Comment</button><button onClick={()=>void addReview('revisit')}><kbd>R</kbd> Revisit</button><button onClick={()=>void addReview('question')}><kbd>?</kbd> Question</button><button onClick={()=>void addReview('cut')}><kbd>X</kbd> Cut?</button></>}</div>}
 {mode==='audit'&&<aside className="gv-audit-rail">{active?<><div className="gv-audit-nav"><div className="gv-audit-count">{activeReview+1} / {openReviews.length}</div><div className="gv-audit-nav-buttons"><button onClick={()=>goReview(activeReview-1)}>↑ Previous</button><button onClick={()=>goReview(activeReview+1)}>↓ Next</button></div></div><div className={`gv-review-kind kind-${active.kind}`}>{kindLabel[active.kind]}</div><blockquote title={active.selectedText}>{reviewExcerpt(active.selectedText)}</blockquote>{active.comment&&<p>{active.comment}</p>}{active.reviewerName&&<span className="gv-reviewer-name">— {active.reviewerName}</span>}<div className="gv-audit-actions"><button className="gv-resolve" onClick={()=>void resolveActive()}>Resolve <kbd>{mod}↵</kbd></button></div></>:<div className="gv-audit-empty"><strong>Review clear.</strong><span>No unresolved review marks.</span></div>}</aside>}
 {shortcutsOpen&&<div className="gv-shortcuts">{mode==='read'?<><span><kbd>C</kbd> comment</span><span><kbd>R</kbd> revisit</span><span><kbd>?</kbd> question</span><span><kbd>X</kbd> cut?</span><span><kbd>Esc</kbd> write</span></>:mode==='audit'?<><span><kbd>⌥↓</kbd> next</span><span><kbd>⌥↑</kbd> previous</span><span><kbd>{mod}↵</kbd> resolve</span><span><kbd>{mod}1</kbd> write</span><span><kbd>{mod}2</kbd> read</span></>:<><span><kbd>{mod}N</kbd> new note</span><span><kbd>{mod}S</kbd> scratch</span><span><kbd>{mod}D</kbd> today</span><span><kbd>{mod}K</kbd> navigate</span><span><kbd>{mod}2</kbd> read</span><span><kbd>{mod}3</kbd> audit</span></>}</div>}
 {!isScratch&&<ShareReviewPanel open={shareOpen} notePath={note.path} title={displayTitle} markdown={currentContent()} onClose={()=>setShareOpen(false)} onImported={()=>void reloadReviews()}/>} 
 <div className="gv-statusbar"><div className="gv-statusbar-stats"><span className="gv-stat"><span className={`gv-stat-dot ${saveState}`}/>{saveLabel}</span><span className="gv-stat">{words} words</span><span className="gv-stat">{chars} chars</span><span className="gv-stat">{readingTime(words)}</span></div><div className="gv-statusbar-actions"><button className="gv-shortcuts-btn" onClick={()=>setShortcutsOpen(v=>!v)}>Shortcuts</button>{!isScratch&&<button className="gv-share-review-btn" onClick={()=>{setShortcutsOpen(false);setShareOpen(v=>!v)}}>Share for Review</button>}{!isScratch&&<button className="gv-export-pdf" onClick={handleExportPdf} title="Export this note as PDF">Export PDF</button>}</div></div></div>
})
export default Editor